setw -g mode-keys vi
setw -g status-keys vi

# colemak keyboard map in copy mode
bind -T copy-mode-vi 'u' send-keys -X cursor-up
bind -T copy-mode-vi 'e' send-keys -X cursor-down
bind -T copy-mode-vi 'n' send-keys -X cursor-left
bind -T copy-mode-vi 'i' send-keys -X cursor-right
